### ISSUE TITLE
Moops with `eval`

### ISSUE THREAD

**Issue by barefootcoder** [tobyink/p5-moops#4]
Maybe I'm doing something wrong here, or maybe it's just my version of Perl.
```
[absalom:~] perl -MMoops -le 'class Foo {}'
[absalom:~] perl -MMoops -le 'eval q|class Foo {}|'
Segmentation fault
[absalom:~] perl -v

This is perl 5, version 14, subversion 4 (v5.14.4) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2013, Larry Wall
```
(etc)

Can I not `eval` a Moops class?

**Comment by tobyink** [comment]
Works for me under Perl 5.26.2.

The keyword API was first introduced in 5.14, so perhaps its initial implementation was buggy?

**Comment by barefootcoder** [comment]
Okay.  I'll try to Perlbrew up some different versions and figure out what's going on.

**Comment by barefootcoder** [comment]
Okay, after multiple `perlbrew` builds on multiple machines, it appears that there was just something flaky with that particular 5.14 build on that particular machine.  After upgrading `perlbrew` and rebuilding the `perl` from scratch, the problem has disappeared.  Soooo ... yeah.  No clue what happened, but I guess there's no real problem, so I'm closing the issue.

**Comment by tobyink** [comment]
Okay, well, thanks for investigating!
